### ISSUE TITLE
Fatal error on v1.4.0

### ISSUE THREAD

**Issue by serhumanos** [gandhihitesh9/post-meta-data-manager#5]
After the last update to version 1.4.0 a Fatal error appears:

"Fatal error: Uncaught Error: Class "Automattic\WooCommerce\Utilities\OrderUtil" not found in /media/data/Biblioteca/Rendo/Actividades/Teorema/Proyecto/Teorema II - Sitio Web/VirtualHost/WordPress/wp-content/plugins/post-meta-data-manager/includes/admin/class-pmdm-wp-admin.php on line 48"

![image](https://github.com/user-attachments/assets/8446b2b9-9003-41d2-b4ea-bb5ec3f678f0)

Server info:
Arquitectura del servidor	Linux 6.5.0-41-generic x86_64
Servidor web	Apache/2.4.52 (Ubuntu)
Versión de PHP	8.3.6 (Admite valores de 64 bits)
PHP SAPI	apache2handler
PHP max input variables	1000
Límite de tiempo de PHP	60
Límite de memoria PHP	256M
Tiempo máximo de entrada	60
Tamaño máximo subida de archivo	128M
PHP post max size	128M
Versión de cURL	7.81.0 OpenSSL/3.0.2
¿Está SUHOSIN instalado?	No
¿Está disponible la biblioteca Imagick?	Sí
¿Es compatible con enlaces permanentes bonitos?	Sí
Reglas de .htaccess	Tu archivo .htaccess solo contiene características del núcleo de WordPress.
Hora actual	2024-07-13T16:43:20+00:00
Hora actual UTC	Saturday, 13-Jul-24 16:43:20 UTC
Hora actual del servidor	2024-07-13T12:43:18-04:00

DATABASE
Extensión	mysqli
Versión del servidor	10.6.16-MariaDB-0ubuntu0.22.04.1
Versión del cliente	mysqlnd 8.3.6
Usuario de la base de datos	wordpress
Servidor de la base de datos	localhost
Nombre de la base de datos	wordpress
Prefijo de la tabla	wp_
Mapa de caracteres de la base de datos	utf8mb4
Compilación de la base de datos	utf8mb4_unicode_520_ci
Tamaño máximo permitido del paquete	16777216
Número máximo de conexiones	151

thanks for this useful plugin!

**Comment by gandhihitesh9** [comment]
Hi @serhumanos 
Thanks for reporting the issue. 
We solved it and uploaded on wp plugin directory.

Please update to the latest version. 1.4.1

Thanks,
Hitesh

**Comment by serhumanos** [comment]
hi @gandhihitesh9 
thankyou for your quickly support!

the problem was solved!
