### ISSUE TITLE
PMDM not shown in custom taxonomy

### ISSUE THREAD

**Issue by serhumanos** [gandhihitesh9/post-meta-data-manager#7]
I have created a new custom taxonomy 'Locations' for a custom post type called 'Register' and selected both options in the PMDM settings. However, PMDM data is only shown in the custom post type "Register", but not in the "Locations" custom taxonomy.

thanks!

**Comment by gandhihitesh9** [comment]
Hi @serhumanos 

Have you enabled PMDM for the newly created custom taxonomy from the PMDM settings page?

![image](https://github.com/user-attachments/assets/b9696b75-2bf7-456a-aaf0-f428562da9cb)

Thanks,
Hitesh

**Comment by serhumanos** [comment]
hi @gandhihitesh9, answering your question,  yes, I have both of them (the custom post type and the custom taxonomy) in the PMDM settings.

if you can't reproduce, tell me to generate more tests.

thank you for you time!

**Comment by gandhihitesh9** [comment]
Hi @serhumanos ,

Ok one more question.
Is taxonomy created through code or any plugin?

If you can check below parameter values then I can get some ideas.
- **public**
- **publicly_queryable**

Thanks,
Hitesh

**Comment by serhumanos** [comment]
The custom taxonomy was created with ACF Plugin, and the parameters "public" and "publicly_queryable" are setted on:

<img src="https://github.com/user-attachments/assets/9523c70d-19b8-4106-aa80-216a7a869eda" width="600">

<img src="https://github.com/user-attachments/assets/4780aa55-fc6b-49a6-b624-2c9e934be784" width="400">

the custom post type show PMDM ok:
<img src="https://github.com/user-attachments/assets/0dde7369-53a1-4f5b-9a6d-12adab387e4f" width="400">

the custom tax not:
<img src="https://github.com/user-attachments/assets/46027015-7c5a-4da1-836d-06c0ad0b905f" width="400">

**Comment by gandhihitesh9** [comment]
Hello @serhumanos 

Is that possible to create a testing/staging environment for your website? So, I can quickly review it.

Thanks,
Hitesh

**Comment by serhumanos** [comment]
Hi @gandhihitesh9,

I think I can set up a testing site, but not right now as I'm short on time. I'll let you know if there are any updates. In the meantime, I'll do some tests with older versions.

Thanks again for your willingness and time.

**Comment by gandhihitesh9** [comment]
Hi @serhumanos 

Going to close this issue for now. You can create new one in the future.
