### ISSUE TITLE
Problem deleting meta when NOT using HPOS

### ISSUE THREAD

**Issue by rafwlaz** [gandhihitesh9/post-meta-data-manager#9]
There is an error when trying to delete meta not using HPOS.

To fix need in `post-meta-data-manager/includes/admin/class-pmdm-wp-admin.php` on line `175` change `if` to
```
if ( class_exists( OrderUtil::class ) && OrderUtil::custom_orders_table_usage_is_enabled() ) {
				$order = wc_get_order( $post_id );
				if ( $order ) {
					// HPOS
``` 

Because `OrderUtil` class exists and we need immediately to check if HPOS is turned on.

**Comment by gandhihitesh9** [comment]
Hello @rafwlaz 

Thanks for reporting the issue.

I will implement your code suggestion in the plugin and solve that delete meta issue.

Thanks,
Hitesh Gandhi

**Comment by gandhihitesh9** [comment]
Hi @rafwlaz 

I just solved this issue, Please check & confirm.

Thanks,
Hitesh Gandhi

**Comment by rafwlaz** [comment]
@gandhihitesh9 now all looks good, thanks for fast resolve :)
